spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    net.ifaye.ecommerce.order : TRACE
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB #make log file rolling any time it reaches 5MB
      max-history: 7 #Delete file after 7 days of retention
      #file-name-pattern: ${LOG_FILE}_%d{yyyy-MM-dd}_%i.gz